services:
  - type: web
    name: konbini-gacha
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SCRAPE_TOKEN
        generateValue: true
